### ISSUE TITLE
Integrer raven-python (sentry client)

### ISSUE THREAD

**Issue by gregtap** [peopledoc/insight-reloaded#1]
https://github.com/getsentry/raven-python

**Comment by Natim** [comment]
Should we use logging configuration? http://raven.readthedocs.org/en/latest/config/logging.html

**Comment by gregtap** [comment]
That would be nicer yes.

**Comment by Natim** [comment]
I think I will use dictConfig with LOGGING defined in a settings.py http://raven.readthedocs.org/en/latest/config/logging.html

**Comment by Natim** [comment]
The code is here, we may want to test if we are logging what do we except.
