### ISSUE TITLE
[qualif] new redis server

### ISSUE THREAD

**Issue by SwannCroiset** [peopledoc/insight-reloaded#37]
A new Redis server is available on Qualif, you need to re-configure your app to use it (the old one will be stopped):

`redis.qualif.people-doc.net:6379 (ip 192.168.3.44)`

ref: https://github.com/peopledoc/peopleinfra/issues/502

**Comment by SwannCroiset** [comment]
ok for REDIS_DB = "7"

**Comment by SwannCroiset** [comment]
any ETA ?

**Comment by FlogFr** [comment]
I just added Stunnel on converter qualif machine `converter.qualif.people-doc.net`, so the new redis server is now available at the `127.0.0.1 localhost` port `6379` :)
Ping @pabluk / @ccouturi : can we change manually the settings or there is a devops on this project?

**Comment by ccouturi** [comment]
I don't know what is this project

**Comment by FlogFr** [comment]
ping @toopy ?

**Comment by toopy** [comment]
@ewjoachim ?

**Comment by ewjoachim** [comment]
https://peopledoc.slack.com/archives/C0J5U254G/p1508511770000315
> swann: dernière release en juillet 2014
coté owner: aucun salarié de PeopleDoc depuis le départ des deux principaux contributeurs
coté status: buggué jusqu'à la moelle avec un temps de vie d'un processus de quelques heures à quelques jours, remplacé par sae-preview sur tous les envs depuis avril 2017
