### ISSUE TITLE
Priority queue

### ISSUE THREAD

**Issue by gregtap** [peopledoc/insight-reloaded#9]
We need a way to give a high priority to uploaded docs VS distributed docs.

You could either have dedicated workers or having your workers listening to two queues,  switching from Qlow to Qhigh every second.

**Comment by Natim** [comment]
I think the best way to do that an keep insight as simple as possible would be to serve the API on two urls.

http://urgent-insight.yourdomain.com and http:/normal-insight.yourdomain.com.

**Comment by Natim** [comment]
Ok so I change a little bit my proposition : https://github.com/novagile/insight-reloaded/commit/69f04376499f84c14a5b187fcc07acc7a58d983c
